### ISSUE TITLE
"panic: runtime error" when doing a multiple call using "&&"

### ISSUE THREAD

**Issue by DrBomb** [cesanta/mos-tool#20]
```
C:\Users\Juan\Repos\esp32\V1.0\apps\FlowChem1>mos flash --esp-baud-rate 1152000 && mos wifi "Los compadres" fabianamelo16 && mos config-set device.id=test1 && mos console
Loaded FlowChem1/esp32 version 1.0 (20180928-042222)
Using port COM3
Opening COM3 @ 115200...
Connecting to ESP32 ROM, attempt 1 of 10...
  Connected, chip: ESP32D0WDQ6 R1
Running flasher @ 1152000...
  Flasher is running
Flash size: 4194304, params: 0x0220 (dio,32m,40m)
Deduping...
    20864 @ 0x1000 -> 4480
     3072 @ 0x8000 -> 0
    16384 @ 0x9000 -> 8192
     8192 @ 0xd000 -> 0
   262144 @ 0x190000 -> 28672
Writing...
     4096 @ 0x1000
     4096 @ 0x6000
     8192 @ 0x9000
  1155072 @ 0x10000
     8192 @ 0x1ae000
    20480 @ 0x1b2000
Wrote 1195200 bytes in 14.73 seconds (633.96 KBit/sec)
Verifying...
    20864 @ 0x1000
     3072 @ 0x8000
    16384 @ 0x9000
     8192 @ 0xd000
  1153856 @ 0x10000
   262144 @ 0x190000
Booting firmware...
All done!
Using port COM3
Getting configuration...
Setting new configuration...
Saving and rebooting...
Using port COM3
Getting configuration...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x6fc6ac]

goroutine 1 [running, locked to thread]:
cesanta.com/fw/defs/config.(*_Client).Get(0x1420cf60, 0xc5d8c0, 0x140d41c0, 0x140840f8, 0xc5d8c0, 0x140d41c0, 0x140840f0, 0xc573b0, 0x14164180)
        /go/src/cesanta.com/fw/defs/config/config_service.go:71 +0x12c
cesanta.com/mos/dev.(*DevConn).GetConfig(0x1424e160, 0xc5d8a0, 0x140ea0bc, 0x0, 0x0, 0x0)
        /go/src/cesanta.com/mos/dev/dev_conn.go:78 +0x118
cesanta.com/mos/config.SetWithArgs(0xc5d8a0, 0x140ea0bc, 0x1424e160, 0x1421a278, 0x1, 0x1, 0xa0be6d, 0xc5d8a0)
        /go/src/cesanta.com/mos/config/config.go:80 +0x70
cesanta.com/mos/config.Set(0xc5d8a0, 0x140ea0bc, 0x1424e160, 0x0, 0x0)
        /go/src/cesanta.com/mos/config/config.go:68 +0x5f
main.run(0x1420a180, 0xc5d8a0, 0x140ea0bc, 0x1424e160, 0x0, 0x0)
        /go/src/cesanta.com/mos/main.go:147 +0x6c
main.main()
        /go/src/cesanta.com/mos/main.go:266 +0x6c0
```

**Comment by rojer** [comment]
fix for the crash is incoming.

as a side note, it looks like you are doing two `mos config-set` operations one after another. you are better off combining them into two or maybe using `--no-reboot` on all but the last one.
