### ISSUE TITLE
mos debug-core-dump fails to invoke debugger properly

### ISSUE THREAD

**Issue by DrBomb** [cesanta/mos-tool#26]
Invoking `mos debug-core-dump` fails to complete the debug setup, while doing it the "old way" still works.

Complete log:

```
ubuntu@ubuntu-xenial:/vagrant/V1.0/apps/TecoSM$ mos debug-core-dump console.log
Core dump by TecoSM/esp32 1.0 20181116-050852
Using ELF file at: /vagrant/V1.0/apps/TecoSM/build/objs/fw.elf
Using Docker image: docker.io/mgos/esp32-build:3.1-r4
Running docker run --rm -i --tty=true -v /vagrant/V1.0/apps/TecoSM/build/objs/fw                                                                                                                                                             .elf:/fw.elf -v console.log:/core -v /vagrant/V1.0/apps/TecoSM:/vagrant/V1.0/app                                                                                                                                                             s/TecoSM docker.io/mgos/esp32-build:3.1-r4 bash -c /usr/local/bin/serve_core.py                                                                                                                                                              --rom=/opt/Espressif/rom/rom.bin --rom_addr=0x40000000 --xtensa_addr_fixup=true                                                                                                                                                              /fw.elf /core & $MGOS_TARGET_GDB /fw.elf -ex 'target remote 127.0.0.1:1234' -ex                                                                                                                                                              'set confirm off' -ex bt
GNU gdb (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-build_pc-linux-gnu --target=xtensa-esp                                                                                                                                                             32-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /fw.elf...Waiting for gdb on 1234
done.
Remote debugging using 127.0.0.1:1234
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 46732)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_nobloc                                                                                                                                                             k
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/bin/serve_core.py", line 189, in handle
    self._core = core = Core(args.log)
  File "/usr/local/bin/serve_core.py", line 74, in __init__
    self._dump = self._read(filename)
  File "/usr/local/bin/serve_core.py", line 112, in _read
    with open(filename) as f:
IOError: [Errno 21] Is a directory: '/core'
----------------------------------------
Remote connection closed
No stack.
(gdb)
(gdb) bt
No stack.
(gdb) exit
Undefined command: "exit".  Try "help".
(gdb) exit
Undefined command: "exit".  Try "help".
(gdb) q
ubuntu@ubuntu-xenial:/vagrant/V1.0/apps/TecoSM$ make -C ./deps/modules/mongoose-os/fw/platforms/esp32 debug_coredump CONSOLE_LOG=$(pwd)/console.log ELF_FILE=$(ls $PWD/build/objs/fw.elf)
make: Entering directory '/vagrant/V1.0/apps/TecoSM/deps/modules/mongoose-os/fw/platforms/esp32'
GNU gdb (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-build_pc-linux-gnu --target=xtensa-esp32-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /app.elf...Waiting for gdb on 1234
done.
Remote debugging using 127.0.0.1:1234
Found core at 23 - 454390
Mapping DRAM: 335872 @ 0x3ffae000
Mapping /opt/Espressif/rom/rom.bin at 0x40000000
Mapping /app.elf .rtc.text: 52 @ 0x400c0000
Mapping /app.elf .rtc.dummy: 52 @ 0x3ff80000
Mapping /app.elf .iram0.vectors: 1024 @ 0x40080000
Mapping /app.elf .iram0.text: 79660 @ 0x40080400
Mapping /app.elf .dram0.data: 11092 @ 0x3ffb0000
Mapping /app.elf .dram0.bss: 35232 @ 0x3ffb2b58
Mapping /app.elf .flash.rodata: 200964 @ 0x3f400020
Mapping /app.elf .flash.text: 877498 @ 0x400d0018
Loaded core dump from last snippet in  /console.log
0x4008fc2b in invoke_abort ()
    at /opt/Espressif/esp-idf/components/esp32/panic.c:155
155             *((int *) 0) = 0;
add symbol table from file "/opt/Espressif/rom/rom.elf" at
        .text_addr = 0x40000000
Reading symbols from /opt/Espressif/rom/rom.elf...(no debugging symbols found)...done.
(gdb) bt
#0  0x4008fc2b in invoke_abort ()
    at /opt/Espressif/esp-idf/components/esp32/panic.c:155
#1  0x4008fdb0 in abort ()
    at /opt/Espressif/esp-idf/components/esp32/panic.c:170
#2  0x400d2096 in __assert_func (
    file=0x3f40a371 "/vagrant/Dosing/libs/dosing_common/src/mgos_dosing_common.c", line=34, func=<optimized out>,
    failedexpr=0x3f40a57c "dosing->config_setters.pump_speed_set")
    at ../../../.././newlib/libc/stdlib/assert.c:63
#3  0x400f7a98 in mgos_dosing_common_assert_all_f_pointers (
    dosing=0x3ffb8f40 <dosing1>)
    at /vagrant/Dosing/libs/dosing_common/src/mgos_dosing_common.c:21
#4  mgos_dosing_common_start (dosing=0x3ffb8f40 <dosing1>)
    at /vagrant/Dosing/libs/dosing_common/src/mgos_dosing_common.c:46
#5  0x400fd470 in mgos_DosingDummy_init ()
    at /vagrant/Dosing/libs/DosingDummy/src/mgos_DosingDummy.c:162
#6  0x400e64c7 in mgos_deps_init ()
    at /vagrant/V1.0/apps/TecoSM/build/gen/mgos_deps_init.c:251
#7  0x400e2bda in mgos_init () at /mongoose-os/fw/src/mgos_init.c:25
#8  0x400e27f1 in mgos_init2 () at /mongoose-os/fw/src/mgos_hal_freertos.c:195
#9  0x40083063 in mgos_task (arg=0x0)
    at /mongoose-os/fw/src/mgos_hal_freertos.c:206
(gdb) q
Detaching from program: /app.elf, Remote target
Remote doesn't know how to detach
GDB closed the connection
make: Leaving directory '/vagrant/V1.0/apps/TecoSM/deps/modules/mongoose-os/fw/platforms/esp32'
```

**Comment by DrBomb** [comment]
This is on a ESP32 build

**Comment by rojer** [comment]
```
$ mos debug-core-dump console.log
...
IOError: [Errno 21] Is a directory: '/core'
```
oh yeah, time to squash this little one.
for now, as a workaround, use absolute path to console.log: 
```
$ mos debug-core-dump $PWD/console.log
```

**Comment by rojer** [comment]
fix submitted
